# Generated by Django 5.2.6 on 2025-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_checkout_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на оплату'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID цены Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID продукта Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID сессии Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(
                choices=[
                    ('cash', 'Наличные'),
                    ('transfer', 'Перевод на счет'),
                    ('stripe', 'Stripe'),
                ],
                max_length=20,
                verbose_name='Способ оплаты',
            ),
        ),
    ]
